edition = "2021"


reorder_imports = true              # Reorder import statements alphabetically.
fn_single_line = true               # Put single expression functions on a single line.
format_code_in_doc_comments = true
merge_derives = false               # Merge multiple derives into a single one.
normalize_comments = true           # Convert /* */ comments to // comments where possible.
normalize_doc_comments = true       # Convert #![doc] and #[doc] attributes to //! and /// doc comments.
reorder_impl_items = true           # Force order to be type and const first then macros and methods.
space_after_colon = true            # Leave a space after a : type
space_before_colon = false
use_field_init_shorthand = true     # Automatically format structs with key equal to variable name.
